CREATE TABLE productos
(
    id               BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    slug             VARCHAR(255)   NOT NULL UNIQUE,
    nombre           VARCHAR(255)   NOT NULL,
    descripcion      TEXT           NOT NULL,
    ingredientes     TEXT           NOT NULL,
    info_nutricional TEXT,
    precio           NUMERIC(10, 2) NOT NULL CHECK (precio >= 0),
    precio_original  NUMERIC(10, 2) CHECK (precio_original >= 0),
    categoria        VARCHAR(20)    NOT NULL,
    subcategoria     VARCHAR(20),
    helado_tipo      VARCHAR(20),
    helado_sabor     VARCHAR(20),
    kit_tipo         VARCHAR(20),
    mix_tipo         SMALLINT,
    special_type     VARCHAR(30),
    badge            VARCHAR(50),
    badge_type       VARCHAR(20),
    variant_type     VARCHAR(20),
    variant_label    VARCHAR(50),
    en_stock         BOOLEAN        NOT NULL DEFAULT true,
    rating           NUMERIC(2, 1)  NOT NULL DEFAULT 0 CHECK (rating BETWEEN 0 AND 5),
    cantidad_resenas INTEGER        NOT NULL DEFAULT 0,
    imagen_principal VARCHAR(500)   NOT NULL,
    imagenes_galeria TEXT[]         NOT NULL DEFAULT '{}',
    creado_en        TIMESTAMPTZ    NOT NULL DEFAULT now(),
    actualizado_en   TIMESTAMPTZ    NOT NULL DEFAULT now()
);